language: c

sudo: false

matrix:
  - os: linux
    sudo: false
  - os: osx
    before_install:
      - brew install bison
      - export PATH="/usr/local/opt/bison/bin:$PATH"

env:
  - MRUBY_CONFIG=travis_config.rb
script: "rake gensym && rake -m all && rake test"
